name: Build and Release Python Package
on:
  push:
    tags:
      - 'v*.*.*'  # Bất kỳ tag nào dạng v1.0.0 sẽ kích hoạt workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ftputil
          path: dist/ftputil 
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ftputil

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/ftputil
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}